import json

def createIndex():
    preHTML = """
<!DOCTYPE html>
<html>
    <head>
        <title>Cidades</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-pale-green">
                <h1>Lista de Cidades</h1>
            </header>
            
            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
"""
    postHTML = """
                </ul>
            </div>
            <footer class="w3-container w3-pale-green">
                <h5>Generated by TPC2App::EngWeb2024::a95454</h5>
            </footer>            
        </div>
    </body>
</html> 
"""
    with open("mapa-virtual.json") as f:
        bd = json.load(f)
    conteudo = ""

    for city in bd['cidades']:
        conteudo += f"""
                    <li>
                        <a href="http://localhost:7777/{city["id"]}">{city["nome"]}</a>
                    </li>"""
    pagHTML = preHTML + conteudo + postHTML
    f = open('cidades/index.html', 'w')
    f.write(pagHTML)
    f.close()

def createPages():
    with open("mapa-virtual.json") as f:
        bd = json.load(f)
    for city in bd['cidades']:
        pagHTML = f"""
<!DOCTYPE html>
<html>
    <head>
        <title>{city["nome"]}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="w3.css">
        <meta charset="utf-8">
    </head>
    <body>
        <div class="w3-card-4 w3-container">
            <header class="w3-container w3-pale-green w3-center">
                <h1>{city["nome"]}</h1>
            </header>
            <div>
                <h3>Informações</h3>
                    <p><b>ID: </b>{city["id"]}</p>
                    <p><b>Nome: </b>{city["nome"]}</p>
                    <p><b>População: </b>{city["população"]}</p>
                    <p><b>Descrição: </b>{city["descrição"]}</p>
                    <p><b>Distrito: </b>{city["distrito"]}</p>
"""
        pagHTML += """
                <h3>Ligações</h3>
                    <table class="w3-table-all w3-card-4">
                        <tr class="w3-pale-green">
                            <th>ID</th>
                            <th>Destino</th>
                            <th>Distância</th>
                        </tr>
"""
        for l in bd['ligacoes']:
            if l['origem'] == city['id']:
                for c in bd['cidades']:
                    if c['id'] == l['destino']:
                        pagHTML += f"""
                        <tr>
                            <td>{l['id']}</td>
                            <td><a href="http://localhost:7777/{l["destino"]}">{c['nome']}</a></td>
                            <td>{l['distância']}</td>
                        </tr>
"""
        pagHTML += """
                    </table>
            </div>
            <footer class="w3-container w3-pale-green">
                <h5>Generated by TPC2App::EngWeb2024::a95454</h5>
            </footer>    
        </div>
    </body>
</html>
"""
        with open(f'cidades/{city["id"]}.html', 'w') as f:
            f.write(pagHTML)

createIndex()
createPages()